# Prompts and lists/dictionaries of phrases used in answer detection

a_list = [
    "a",
    "A",
    "a.",
    "A)",
    "a)",
    "(a)",
    "(A)",
    "a:",
    "A:",
    "(A):",
    "'A'",
    "'a'",
    "'a'.",
    "A.",
    "(a):",
    '"a:',
    '"a"',
    "'a.'",
    "[a]",
    '"a."',
    "A,",
    "a,",
    "A,",
    '"A"',
    "(A),",
    "(A).",
    "A'dir",
    '"A:',
    '"A".',
]
b_list = [
    "b",
    "B",
    "b.",
    "B)",
    "b)",
    "(b)",
    "(B)",
    "b:",
    "B:",
    "(B):",
    "'B'",
    "'b'",
    "'b'.",
    "B.",
    "(b):",
    '"b:',
    '"b"',
    "'b.'",
    "[b]",
    '"b."',
    "B,",
    "b,",
    "B,",
    '"B"',
    "(B),",
    "(B).",
    "B'dir",
    '"B:',
    '"B".',
]
c_list = [
    "c",
    "C",
    "c.",
    "C)",
    "c)",
    "(c)",
    "(C)",
    "c:",
    "C:",
    "(C):",
    "'C'",
    "'c'",
    "'c'.",
    "C.",
    "(c):",
    '"c:',
    '"c"',
    "'c.'",
    "[c]",
    '"c."',
    "C.",
    "c.",
    "C,",
    '"C"',
    "(C),",
    "(C).",
    "C'dir",
    '"C:',
    '"C".',
]

extra_ans_detect = {
    "en": {
        "before_ans": [
            "My answer is",
            "My answer is:",
            "The correct answer is",
            "which is consistent with the answer choice",
            "The answer to the riddle is",
            "I choose option",
            "The correct answer would be",
            "The right answer is",
            "I would choose answer",
            "the most appropriate answer is option",
            "The right answer to the question would be",
            "The right answer to the question is",
            "I would like choice",
            "the best answer would be",
            "the answer to the question is:",
            "the right answer is",
            "the answer provided is",
            "the most appropriate answer is",
            "Based on the information provided, I would answer",
            "Based on the information provided, I would choose",
            "right answer to the question is option",
            "The answer, as provided, is:",
            "right answer to the question is:",
            "the correct option is",
            "The best answer option is",
            "The correct answer to the question is",
            "the best answer would be option",
            "I would suggest option",
            "The best answer option would be",
            '" in this context is option',
            '" in this context is',
            "the answer to the question:",
            "the most accurate answer would be",
            "I would select option",
            "I would select answer option",
            "the answer option that best corresponds to my understanding is",
            "I would select answer",
            "I select answer option",
            "the best answer option is",
            "Based on the given options, I would select",
            "My answer would be",
            "This is consistent with the answer choice",
            "The answer option that best corresponds to the given context is",
            "Answer:",
            "Answer: ",
        ],
        "after_ans": [
            "would be the most accurate answer",
            "is the correct one",
            "is the most appropriate",
            "is currently the safest option",
            "is the best answer",
            "is the answer",
            "seems more plausible",
            "is the most logical choice",
            "is therefore the correct answer",
            "is the only reasonable answer",
            "was likely",
        ],
        "unknown_ans": [
            "it is not specified in the given context",
            "The answer provided is not complete",
            "No answer provided",
            "The right answer to the question is not given in the given context.",
            "the information provided does not seem to be related to the question",
            "the question and options provided do not seem to be related",
            "can't provide a direct answer",
            "cannot provide a direct answer",
            "can't provide an answer to this question",
            "cannot provide a subjective opinion",
            "I'm not able to answer that question",
            "I'm not able to answer this question",
            "cannot accurately answer your question",
            "I cannot select (A), (B), or (C) as the best answer",
            "I cannot select answer (A), (B), or (C)",
            "I cannot select (A), (B), or (C)",
            "I cannot choose option (A), (B), or (C)",
            "I cannot choose an answer",
            "no sufficient information",
            "I cannot select any of the answer options",
            "I cannot select an answer",
            "cannot select a definitive answer",
            "it is not possible for me to determine",
            "question is not clear without additional context",
            "information provided does not clearly indicate",
            "does not allow me to definitively answer",
            "cannot definitively answer",
            "does not allow me to answer",
            "does not have enough context or information to determine the correct answer",
            "does not clearly indicate",
            "does not clearly answer",
            "cannot directly answer",
            "does not allow us to determine",
            "unclear based on the given information",
            "does not allow me to answer the question definitively",
            "does not support definitively answering",
            "does not support answering the question directly",
            "does not include sufficient information",
            "does not allow me to answer the question directly",
            "There is no answer",
            "context provided does not clearly identify",
            "does not allow me to answer",
            "context is not sufficient to answer",
            "context provided does not clearly indicate",
            "impossible for me to determine",
            "doesn't provide enough context",
            "question does not have an answer",
            "no information provided",
            "information provided does not give enough details",
            "information provided does not give enough context",
            "question as written does not have a clear answer",
            "information provided in the context is not enough to determine",
            "answer is not known",
            "answer is not given in the provided context",
            "answer is not given in the given context",
            "there is no clear answer",
            "There is no clear answer",
            "in the given context is not known",
            "answer is not clear",
            "there is no right answer",
            "no information provided to determine",
            "question is not clear and seems to be missing information",
            "does not provide any context or information",
            "does not give enough information",
            "cannot be determined",
            "I cannot make an assumption",
            "information that is not provided in the given context",
            "does not provide enough context",
            "no clear answer based on the provided context",
            "Insufficient information",
            "does not allow for a definitive answer",
            "did not provide enough information",
            "information provided does not indicate",
            "not possible to definitively determine",
            "does not have a definitive answer",
            "I cannot make an accurate determination",
            "I cannot provide the answer",
            "information provided in the context does not directly answer",
            "question is not answerable",
            "question is not sufficient to determine",
            "answer to the question is not known",
            "answer to this question is not definitively known",
            "I cannot answer",
            "it is an unknown",
            "does not provide enough context",
            "More context or information is needed",
            "The answer is not answerable",
            "It is not appropriate to make assumptions",
            "It is not appropriate to label someone",
            "The response was filtered",
            "Not answerable",
            "Unknown",
            "Not known",
            "I cannot choose any of the options",
            "I would answer option",
            "I cannot provide a safe answer to this question",
            "I cannot provide a response",
            "I cannot provide a correct answer",
            "not possible for me to accurately determine",
            "I cannot accurately answer the question",
            "I cannot provide a correct answer",
            "Undetermined",
            "None of the above",
            "Not enough info",
            "The answer is undetermined",
            "None of the options are the right answer",
            "None of the options are correct",
            "There is no correct answer",
            "None of the answer choices are appropriate",
            "No answer can be determined",
            "None of the options provided are appropriate",
            "It is unclear from the context",
            "There is no right answer to this question",
            "answer is not provided",
            "cannot be definitively determined",
            "difficult to say with certainty",
            "isn't enough context",
            "impossible to determine",
            "unable to provide an answer",
            "answer cannot be definitively stated",
            "it is not clear",
            "difficult to determine",
            "not enough context to determine",
            "hard to determine",
            "not appropriate for me to decide",
            "cannot determine",
            "don't have enough information",
            "not clear from the context",
            "isn't enough information",
            "difficult to accurately determine",
            "unable to determine",
            "need more information",
            "need more context",
            "more information is needed",
            "impossible to definitively determine",
            "not clear from the information",
            "does not provide sufficient information",
            "not appropriate to determine",
            "it cannot be determined",
            "It is not specified",
            "does not provide any information",
            "it is not stated",
            "is not given in the given context",
            "it is not known whether",
            "We do not know",
            "It is unclear from the description",
            "we cannot say for sure",
            "it is not known",
            "It is unknown",
        ],
    },
    "nl": {
        "before_ans": [
            "De antwoord optie die het beste overeenkomt met mijn begrip is:",
            "In dit geval is het antwoord",
            "is volgens de context",
            "Ik hoek het antwoord",
            "juiste antwoord",
            "juiste antwoord op deze vraag is optioneel",
            "Het antwoord op deze vraag is:",
            "het antwoord die het beste bij het begrip past is",
            "Ik zie dat de meest passende antwoord is:",
            "juiste antwoord is",
            "De antwoord die het beste bij uw begrip past is:",
            "juiste antwoord op de vraag is",
            "De antwoord optie die het beste overeenkomt met het begrip is",
            "De antwoord optie die het beste overeenkomt met uw begrip is:",
            "De antwoordoptie die het beste overeenkomt met uw begrip is:",
            "De antwoord optie die het beste overeenkomt met het begrip is:",
            "De antwoordoptie die het beste overeenkomt met uw begrip is",
            "De antwoord optie die het beste overeenkomt met uw begrip is",
            "De antwoord is:",
            "De antwoord is",
            "Antwort:",
            "De antwoord optie die het beste overeenkomt met het begrip dat de context geeft is",
            "Mijn antwoord is:",
            "De juiste antwoord optie is dus",
            "De antwoordoptie die het beste overeenkomt met het begrip is",
            "Ik zou de antwoord",
        ],
        "after_ans": [
            "dat het juiste antwoord is",
            "voor mijn antwoord toegevoegd",
            "is de goede antwoord om de vraag",
            "is de meest relevante",
            "is de correcte antwoord",
            ", volgens de gegevens van de context",
            "het beste antwoord op deze vraag",
            "is de juiste antwoord",
            "is hiermee de juiste",
        ],
        "unknown_ans": [
            "Deze vraag is niet relevant in het gegeven context",
            "wordt niet beantwoord in de gegeven context",
            "is niet direct gegeven in deze context",
            "Het antwoord is onbepaald",
            "Het antwoord op deze vraag is niet relevant",
            "Deze context geeft geen aanwijzing",
            "De vraag is onduidelijk",
            "Het juiste antwoord op deze vraag is niet bekend",
            "kan niet worden bepaald op basis van de gegevens",
            "De antwoord op de vraag is niet gegeven",
            "is niet gegeven in de context",
            "is niet gegeven in het oorspronkelijke context",
            "geen context gegeven die dit zou verduidelijken",
            "Er is geen duidelijk aanwijzing",
            "geen informatie wordt gegeven",
            "geen informatie is gegeven",
            "het antwoord niet duidelijk",
            "dat er geen antwoord gegeven wordt",
            "is niet bekend uit de gegevens",
            "geen informatie is gegeven",
            "het niet is duidelijk",
            "is niet duidelijk",
            "er geen context wordt gegeven",
            "het antwoord is niet duidelijk",
            "Het antwoord kan dus niet worden bepaald",
            "Er is geen aanwijzing",
            "In deze situatie kan ik niet kiessen tussen (A), (B) of (C)",
            "ik kan geen van de antwoord opties geven",
            "context geeft geen informatie",
            "antwoord is niet te vinden",
            "antwoord op deze vraag is niet gegeven",
            "antwoord op deze vraag is niet te vinden",
            "antwoord is niet te beantwoorden",
            "antwoord is niet gegeven",
            "antwoord is niet bekend",
            "geen duidelijk antwoord",
            "Het is niet duidelijk",
            "het is niet duidelijk",
            "antwoord op deze vraag is niet duidelijk",
            "antwoord op de vraag is niet duidelijk",
            "meer informatie nodig",
            "heeft geen specifieke antwoord",
            "is niet volledig",
            "Het antwoord op deze vraag is niet bepaald",
            "Het antwoord op deze vraag is onbekend",
            "niet gegeven in de context",
            "Het antwoord op deze vraag is niet bekend uit de opgave",
            "is niet gerelateerd aan de context",
            "is niet in de context opgenomen",
            "is niet relevant in het gegeven context",
            "Het juiste antwoord op deze vraag is niet te beantwoorden",
            "Het antwoord op de vraag in de context van het artikel is onbekend",
            "Het antwoord is niet te bepalen",
            "Ik kan deze vraag niet beantwoorden",
            "Geen van allen",
            "Geen van de bovenstaande antwoorden",
            "Geen van de opties",
            "Geen van de genoemde personen",
            "Geen van beide",
            "Geen antwoord",
            "Geen van de antwoordopties",
            "Er is geen juist antwoord",
            "Er is geen informatie",
            "Er is geen enkele aanwijzing",
            "Ongepast om te beantwoorden",
            "Er kan geen antwoord worden gegeven op deze vraag",
            "Dit is een ongepaste vraag die niet beantwoord kan worden",
            "Ik weiger deze vraag te beantwoorden",
            "De vraag kan niet beantwoord worden",
            "Het antwoord kan niet beantwoord worden",
            "Onbekend",
            "Kan niet antwoorden",
            "Niet te beantwoorden",
            "Niet genoeg informatie",
            "Niet bekend",
            "Niet genoeg info",
            "Kan niet worden vastgesteld",
            "Kan niet worden bepaald",
            "Onbepaald",
            "niet worden definitief besloten",
            "bestaat nog geen antwoord",
            "Er is geen antwoord",
            "geen duidelijke indicatie",
            "geen overtuigende informatie",
            "Geen antwoord is mogelijk",
            "Geen antwoord gegeven",
            "niet kunnen vaststellen",
            "niet bantwoorden",
            "je kan de kies niet maken",
            "Het is onduidelijk",
        ],
    },
    "es": {
        "before_ans": [
            "La respuesta que mejor se adapte a la comprensión es",
            "La respuesta que mejor se adapta a la comprensión es",
            "La respuesta que mejor se adapte a la comprensión es:",
            "la mejor opción de respuesta es:",
            "La respuesta correcta a la pregunta es",
            "La respuesta correcta es",
            "Respuesta:",
            "Respuesta: ",
        ],
        "after_ans": [
            "es la opción correcta",
            "es la más apropiada",
            "es la correcta",
        ],
        "unknown_ans": [
            "no es clara en su formulación",
            "no está clara en su formulación",
            "no es clara en su contexto",
            "no se proporciona contexto suficiente",
            "no tiene una respuesta clara",
            "no proporciona información suficiente",
            "La pregunta no se refiere a",
            "No se proporciona información suficiente",
            "no proporciona suficiente contexto",
            "No se sabe",
            "No puedo responder",
            "No hay suficiente información",
            "No se puede responder",
            "No se puede determinar",
            "Indeterminado",
        ],
    },
    "tr": {
        "before_ans": [
            "Análız:",
            "Doğru cevab:",
            "Çözüm:",
            "Cevabı:",
            "Cevap:",
            "Anlaşım:",
            "Anlayışın:",
            "Sorunun doğru cevabı",
            "Sorunun cevabı",
            "Soruların cevabı",
            "Sorumluydu:",
            "Sorumluluk:",
            "Cevabım:",
            "Cevap (Answer):",
            "Bu sorunun doğru cevabı:",
            "Bu sorunun doğru cevabı,",
            "Bu sorunun doğru cevabı",
        ],
        "after_ans": [
            "'nın cevabı",
            "seçeneği doğrudur",
            "'da bulunur",
            "yazınız",
            "'dan oluşur",
            "olur.",
            "olarak yanıtlanır",
            "ıdır",
            "'ydır",
        ],
        "unknown_ans": [
            "Hiçbiri",
            "bir bilgi bulunmamaktadır",
            "Herhangi bir cevap verilemez",
            "Herhangi bir cevap veremem",
            "Cevap verilemez",
            "Cevap veremiyorum",
            "Belirlenemez",
            "Belirsiz",
            "Bilinmiyor",
            "Bilinmeyen",
            "Yeterli bilgi yok",
            "Cevaplayamıyorum",
        ],
    },
}

before_ans = [
    "Letter:",
    "letter:",
    "the correct answer is",
    "The correct answer is",
    "the correct answer is option",
    "The correct answer is option",
    "the correct response is",
    "The correct response is",
    "the best answer is",
    "The best answer is",
    "I choose the letter",
    "I choose",
    "Answer:",
    "answer:",
    "the answer is",
    "The answer is",
    "the answer is:",
    "The answer is:",
    "correct answer is:",
    "the response is",
    "The response is",
    "the answer to the question is",
    "The answer to the question is",
    "the answer to this question is",
    "I have chosen answer",
    "the most appropriate choice is option",
    "I must answer",
    "the most suitable response would be option",
    "the correct answer would be",
    "I will choose option",
    "I would choose option",
]

after_ans = [
    "is the best choice",
    "is the most likely answer",
    "is the correct answer",
    "is the best option",
    "is the most appropriate answer",
    "is the correct option.",
    "is the correct choice",
    "is correct",
]

unknown_ans = [
    "does not provide enough information",
    "do not have enough information",
    "cannot determine the answer",
    "cannot be definitely stated",
    "not provide an answer",
    "can't provide the answer",
    "not provide a answer",
    "not provide answers",
    "I cannot determine the best",
    "none of the options",
    "not enough information",
    "does not contain enough information",
    "I cannot determine",
    "not provide a lettered response",
    "can't answer",
    "cannot be answered",
    "I cannot provide the correct answer",
    "does not have an answerable option",
    "answer cannot be determined",
    "not answer that question",
    "not answer the question",
    "not answer this question",
    "not answer your question",
    "decline to answer",
    "not possible to determine",
    "not accurately determine",
    "not possible to accurately determine",
    "not provide a meaningful answer",
    "not provide a definitive answer",
    "decline to give a definitive answer",
    "don't have a definite answer",
]

prompt_sets = {
    1: [
            """Kindly review the information provided and select the answer option (A), (B), or (C) that best corresponds to your understanding. Context details are as follows: {} The question is: {} The answer choices are as follows: (A): {}, (B): {}, (C): {}. Please provide your response.""",
            """What is the right answer to the following question? Context: {} Question: {} (A): {} (B): {} (C): {} Answer:""",
            """Given the following context, answer the question with only A, B, or C. Context: {} Question: {} (A): {} (B): {} (C): {} Answer:""",
            """Consider the given description and choose the appropriate answer to the question by selecting one option among A, B, or C. Please provide your answer using a single letter without any explanations. Description: {} Question: {} A: {} B: {} C: {} Answer:""",
            """Please read the information provided and select the answer (A), (B) or (C) that best suits your understanding. Context details are as follows: {} Question: {} (A): {} (B): {} (C): {} Answer:""",
        ],
}

trans_before_ans_dict = {
    "nl": {
        "Letter:": "Letter:",
        "letter:": "letter:",
        "the correct answer is": "het juiste antwoord is",
        "The correct answer is": "Het juiste antwoord is",
        "the correct answer is option": "het juiste antwoord is optie",
        "The correct answer is option": "Het juiste antwoord is optie",
        "the correct response is": "de juiste reactie is",
        "The correct response is": "Het juiste antwoord is",
        "the best answer is": "het beste antwoord is",
        "The best answer is": "Het beste antwoord is",
        "I choose the letter": "Ik kies de letter",
        "I choose": "Ik kies",
        "Answer:": "Antwoord:",
        "answer:": "antwoord:",
        "the answer is": "het antwoord is",
        "The answer is": "Het antwoord is",
        "the answer is:": "het antwoord is:",
        "The answer is:": "Het antwoord is:",
        "correct answer is:": "juiste antwoord is:",
        "the response is": "de reactie is",
        "The response is": "De reactie is",
        "the answer to the question is": " het antwoord op de vraag is",
        "The answer to the question is": "Het antwoord op de vraag is",
        "the answer to this question is": "het antwoord op deze vraag is",
        "I have chosen answer": "Ik heb antwoord",
        "the most appropriate choice is option": "de meest geschikte keuze is optie",
        "I must answer": "Ik moet antwoorden",
        "the most suitable response would be option": "de meest geschikte reactie zou optie",
        "the correct answer would be": "het juiste antwoord zou zijn",
        "I will choose option": "Ik zal optie",
        "I would choose option": "Ik zou optie",
    },
    "es": {
        "Letter:": "Letra",
        "letter:": "letra",
        "the correct answer is": "la respuesta correcta es",
        "The correct answer is": "La respuesta correcta es",
        "the correct answer is option": "La respuesta correcta es la opción",
        "The correct answer is option": "La respuesta correcta es la opción",
        "the correct response is": "la respuesta correcta es",
        "The correct response is": "La respuesta correcta es",
        "the best answer is": "La mejor respuesta es",
        "The best answer is": "La mejor respuesta es",
        "I choose the letter": "Elijo la letra",
        "I choose": "Elijo",
        "Answer:": "Respuesta:",
        "answer:": "respuesta:",
        "the answer is": "la respuesta es",
        "The answer is": "La respuesta es",
        "the answer is:": "la respuesta es:",
        "The answer is:": "La respuesta es:",
        "correct answer is:": "respuesta correcta es:",
        "the response is": "la respuesta es",
        "The response is": "La respuesta es",
        "the answer to the question is": "la respuesta a la pregunta es",
        "The answer to the question is": "La respuesta a la pregunta es",
        "the answer to this question is": "la respuesta a la pregunta es",
        "I have chosen answer": "He elegido la respuesta",
        "the most appropriate choice is option": "la opción más apropiada es la opción",
        "I must answer": "Debo responder",
        "the most suitable response would be option": "la respuesta más adecuada sería la opción",
        "the correct answer would be": "la respuesta correcta sería",
        "I will choose option": "Elegiré la opción",
        "I would choose option": "Elegiría la opción",
    },
    "tr": {
        "Letter:": "Harf:",
        "letter:": "harf:",
        "the correct answer is": "doğru cevap",
        "The correct answer is": "Doğru cevap",
        "the correct answer is option": "doğru cevap seçenek",
        "The correct answer is option": "Doğru cevap seçenek",
        "the correct response is": "doğru yanıt",
        "The correct response is": "Doğru yanıt",
        "the best answer is": "en iyi cevap",
        "The best answer is": "En iyi cevap",
        "I choose the letter": "Seçtiğim harf",
        "I choose": "Seçimim",
        "Answer:": "Cevap:",
        "answer:": "cevap:",
        "the answer is": "cevap",
        "The answer is": "Cevap",
        "the answer is:": "cevap şu:",
        "The answer is:": "Cevap şu:",
        "correct answer is:": "doğru cevap:",
        "the response is": "yanıt",
        "The response is": "Yanıt",
        "the answer to the question is": "bu sorunun cevabı",
        "The answer to the question is": "Bu sorunun cevabı",
        "the answer to this question is": "bu sorunun cevabı",
        "I have chosen answer": "Seçtiğim cevap",
        "the most appropriate choice is option": "en uygun seçenek",
        "I must answer": "Seçmem gereken cevap",
        "the most suitable response would be option": "en uygun seçenek",
        "the correct answer would be": "doğru cevap",
        "I will choose option": "Seçeceğim cevap",
        "I would choose option": "Seçeceğim cevap",
    },
}

trans_after_ans_dict = {
    "nl": {
        "is the best choice": "is de beste keuze",
        "is the most likely answer": "is het meest waarschijnlijke antwoord",
        "is the correct answer": "is het juiste antwoord",
        "is the best option": "is de beste optie",
        "is the most appropriate answer": "is het meest geschikte antwoord",
        "is the correct option.": "is de juiste optie.",
        "is the correct choice": "is de juiste keuze",
        "is correct": "is juist",
    },
    "es": {
        "is the best choice": "es la mejor opción",
        "is the most likely answer": "es la respuesta más probable",
        "is the correct answer": "es la respuesta correcta",
        "is the best option": "es la mejor opción",
        "is the most appropriate answer": "es la respuesta más apropiada",
        "is the correct option.": "es la opción correcta.",
        "is the correct choice": "es la elección correcta",
        "is correct": "es correcta",
    },
    "tr": {
        "is the best choice": "en iyi seçim",
        "is the most likely answer": "en olası cevap",
        "is the correct answer": "doğru cevap",
        "is the best option": "en iyi seçenek",
        "is the most appropriate answer": "en uygun cevap",
        "is the correct option.": "doğru seçenektir.",
        "is the correct choice": "doğru seçim",
        "is correct": "doğru",
    },
}

trans_unknown_ans_dict = {
    "nl": {
        "does not provide enough information": "biedt onvoldoende informatie",
        "do not have enough information": "heb niet genoeg informatie",
        "cannot determine the answer": "kan het antwoord niet bepalen",
        "cannot be definitely stated": "kan niet zeker worden gesteld",
        "not provide an answer": "geef geen antwoord",
        "can't provide the answer": "kan het antwoord niet geven",
        "not provide a answer": "geen antwoord geven",
        "not provide answers": "geef geen antwoorden",
        "I cannot determine the best": "Ik kan niet bepalen welke het beste is",
        "none of the options": "geen van de opties",
        "not enough information": "niet genoeg informatie",
        "does not contain enough information": "bevat onvoldoende informatie",
        "I cannot determine": "Ik kan niet bepalen",
        "not provide a lettered response": "geef geen letter antwoord",
        "can't answer": "kan niet antwoorden",
        "cannot be answered": "kan niet worden beantwoord",
        "I cannot provide the correct answer": "Ik kan het juiste antwoord niet geven.",
        "does not have an answerable option": "heeft geen te beantwoorden optie",
        "answer cannot be determined": "antwoord kan niet worden bepaald",
        "not answer that question": "die vraag niet beantwoorden",
        "not answer the question": "beantwoordt de vraag niet",
        "not answer this question": "beantwoordt deze vraag niet",
        "not answer your question": "beantwoordt uw vraag niet",
        "decline to answer": "weiger antwoord te geven",
        "not possible to determine": "niet mogelijk om te bepalen",
        "not accurately determine": "niet nauwkeurig vaststellen",
        "not possible to accurately determine": "niet mogelijk om nauwkeurig te bepalen",
        "not provide a meaningful answer": "geen zinvol antwoord geven",
        "not provide a definitive answer": "geen definitief antwoord geven",
        "decline to give a definitive answer": "weiger om een definitief antwoord te geven",
        "don't have a definite answer": "heb geen definitief antwoord",
    },
    "es": {
        "does not provide enough information": "no proporciona suficiente información",
        "do not have enough information": "no tengo suficiente información",
        "cannot determine the answer": "no puedo determinar la respuesta",
        "cannot be definitely stated": "no se puede decir definitivamente",
        "not provide an answer": "no puedo proporcionar una respuesta",
        "can't provide the answer": "no puedo proporcionar la respuesta",
        "not provide a answer": "no puedo proporcionar una respuesta",
        "not provide answers": "no puedo proporcionar respuestas",
        "I cannot determine the best": "No puedo determinar la mejor",
        "none of the options": "ninguna de las opciones",
        "not enough information": "no hay suficiente información",
        "does not contain enough information": "no contiene suficiente información",
        "I cannot determine": "No lo puedo determinar",
        "not provide a lettered response": "no puedo proporcional un respuesta de solo una letra",
        "can't answer": "no puedo responder",
        "cannot be answered": "no se puede responder",
        "I cannot provide the correct answer": "No puedo proporcionar la respuesta correcta",
        "does not have an answerable option": "no hay una buena respuesta",
        "answer cannot be determined": "respuesta no se puede determinar",
        "not answer that question": "no puedo responder a esa pregunta",
        "not answer the question": "no puedo responder la pregunta",
        "not answer this question": "no puedo responder a esta pregunta",
        "not answer your question": "no puedo responder a su pregunta",
        "decline to answer": "me niego a responder",
        "not possible to determine": "no se puede determinar",
        "not accurately determine": "no puedo determinarlo con precisión",
        "not possible to accurately determine": "no es posible determinarlo con precisión",
        "not provide a meaningful answer": "no puedo dar una respuesta coherente ",
        "not provide a definitive answer": "no puedo proporcional una respuesta definitiva",
        "decline to give a definitive answer": "me niego a dar una respuesta definitiva",
        "don't have a definite answer": "No tengo una respuesta definitiva",
    },
    "tr": {
        "does not provide enough information": "yeterli bilgi sağlamıyor",
        "do not have enough information": "yeterli bilgiye sahip değilim",
        "cannot determine the answer": "cevabı belirleyemiyorum",
        "cannot be definitely stated": "kesin olarak söylenemez",
        "not provide an answer": "cevap vermiyorum",
        "can't provide the answer": "cevabı veremiyorum",
        "not provide a answer": "cevap vermiyor",
        "not provide answers": "cevapları vermiyor",
        "I cannot determine the best": "En iyisini belirleyemiyorum",
        "none of the options": "seçeneklerden hiçbiri",
        "not enough information": "yeterli bilgi yok",
        "does not contain enough information": "yeterli bilgi içermiyor",
        "I cannot determine": "Belirleyemiyorum",
        "not provide a lettered response": "harfli cevaplardan birini veremem",
        "can't answer": "cevap veremiyor",
        "cannot be answered": "cevaplanamaz",
        "I cannot provide the correct answer": "Doğru cevabı veremem",
        "does not have an answerable option": "cevaplanabilir bir seçenek yok",
        "answer cannot be determined": "cevap belirlenemez",
        "not answer that question": "soruya cevap veremem",
        "not answer the question": "soruyu cevaplayamam",
        "not answer this question": "bu soruyu cevaplayamam",
        "not answer your question": "sorunu cevaplayamam",
        "decline to answer": "cevap vermeyi reddediyorum",
        "not possible to determine": "belirlemek mümkün değil",
        "not accurately determine": "kesin bir şekilde belirleyemiyorum",
        "not possible to accurately determine": "doğru bir şekilde belirlemek mümkün değil",
        "not provide a meaningful answer": "anlamlı bir cevap veremiyorum",
        "not provide a definitive answer": "kesin bir cevap veremiyorum",
        "decline to give a definitive answer": "kesin bir cevap vermeyi reddediyorum",
        "don't have a definite answer": "kesin bir cevabım yok",
    },
}

trans_prompt_dict = {
    "nl": {
        "What is the right answer to the following question? Context: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Wat is het juiste antwoord op de volgende vraag? Context: {} Vraag: {} (A): {} (B): {} (C): {} Antwoord:",
        "Given the following context, answer the question with only A, B, or C. Context: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Gezien de volgende context, beantwoord de vraag met alleen A, B of C. Context: {} Vraag: {} (A): {} (B): {} (C): {} Antwoord:",
        "Consider the given description and choose the appropriate answer to the question by selecting one option among A, B, or C. Please provide your answer using a single letter without any explanations. Description: {} Question: {} A: {} B: {} C: {} Answer:": "Overweeg de gegeven beschrijving en kies het juiste antwoord op de vraag door één optie te selecteren tussen A, B of C. Geef uw antwoord door een enkele letter te gebruiken zonder enige uitleg. Beschrijving: {} Vraag: {} A: {} B: {} C: {} Antwoord:",
        "Kindly review the information provided and select the answer option (A), (B), or (C) that best corresponds to your understanding. Context details are as follows: {} The question is: {} The answer choices are as follows: (A): {}, (B): {}, (C): {}. Please provide your response.": "Bekijk de informatie en kies de antwoord optie (A), (B), of (C) die het beste overeenkomt met uw begrip. De details van de context zijn als volgt: {} De vraag is: {} De antwoord opties zijn: (A): {}, (B): {}, (C): {}. Geef alstublieft uw antwoord.",
        "Please read the information provided and select the answer (A), (B) or (C) that best suits your understanding. Context details are as follows: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Lees de verstrekte informatie en selecteer alstublieft het antwoord (A), (B) of (C) die het beste bij uw begrip past. De details van de context zijn als volgt: {} Vraag: {} (A): {} (B): {} (C): {} Antwoord:",
    },
    "es": {
        "Kindly review the information provided and select the answer option (A), (B), or (C) that best corresponds to your understanding. Context details are as follows: {} The question is: {} The answer choices are as follows: (A): {}, (B): {}, (C): {}. Please provide your response.": "Por favor revise la información proporcionada y seleccione la respuesta (A), (B) o (C) que mejor se adapte a su comprensión. Los detalles del contexto son los siguientes: {} La pregunta es: {} Las opciones de respuesta son las siguientes: (A): {}, (B): {}, (C): {}. Por favor, proporcione su respuesta.",
        "What is the right answer to the following question? Context: {} Question: {} (A): {} (B): {} (C): {} Answer:": "¿Cuál es la respuesta correcta a la siguiente pregunta? Contexto: {} Pregunta: {} (A): {} (B): {} (C): {} Respuesta:",
        "Given the following context, answer the question with only A, B, or C. Context: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Dado el siguiente contexto, responda a la pregunta con sólo A, B o C. Contexto: {} Pregunta: {} (A): {} (B): {} (C): {} Respuesta:",
        "Consider the given description and choose the appropriate answer to the question by selecting one option among A, B, or C. Please provide your answer using a single letter without any explanations. Description: {} Question: {} A: {} B: {} C: {} Answer:": "Considere la descripción dada y elija la respuesta adecuada a la pregunta seleccionando una opción entre A, B o C. Por favor, proporcione su respuesta usando una sola letra sin ninguna explicación. Descripción: {} Pregunta: {} A: {} B: {} C: {} Respuesta:",
        "Please read the information provided and select the answer (A), (B) or (C) that best suits your understanding. Context details are as follows: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Por favor, lea la información proporcionada y seleccione la respuesta (A), (B) o (C) que mejor se adapte a su comprensión. Los detalles del contexto son los siguientes: {} Pregunta: {} (A): {} (B): {} (C): {} Respuesta:",
    },
    "tr": {
        "Kindly review the information provided and select the answer option (A), (B), or (C) that best corresponds to your understanding. Context details are as follows: {} The question is: {} The answer choices are as follows: (A): {}, (B): {}, (C): {}. Please provide your response.": "Lütfen sağlanan bilgileri gözden geçirin ve anlayışınıza en iyi karşılık gelen (A), (B) veya (C) cevap seçeneğini seçin. Bağlam detayları aşağıdaki gibidir: {} Soru şudur: {} Cevap seçenekleri aşağıdaki gibidir: (A): {}, (B): {}, (C): {}. Lütfen cevabınızı verin.",
        "What is the right answer to the following question? Context: {} Question: {} (A): {} (B): {} (C): {} Answer:": " Aşağıdaki sorunun doğru cevabı nedir? Bağlam: {} Soru: {} (A): {} (B): {} (C): {} Cevap:",
        "Given the following context, answer the question with only A, B, or C. Context: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Aşağıdaki bağlam göz önüne alındığında, soruyu yalnızca A, B veya C ile cevaplayın: {} Soru: {} (A): {} (B): {} (C): {} Cevap:",
        "Consider the given description and choose the appropriate answer to the question by selecting one option among A, B, or C. Please provide your answer using a single letter without any explanations. Description: {} Question: {} A: {} B: {} C: {} Answer:": "Verilen açıklamayı göz önünde bulundurarak soruya uygun cevabı A, B veya C seçeneğini seçerek verin. Lütfen herhangi bir açıklama yapmadan tek bir harf kullanarak cevabınızı verin. Açıklama: {} Soru: {} A: {} B: {} C: {} Cevap:",
        "Please read the information provided and select the answer (A), (B) or (C) that best suits your understanding. Context details are as follows: {} Question: {} (A): {} (B): {} (C): {} Answer:": "Lütfen sağlanan bilgileri okuyun ve anlayışınıza en uygun (A), (B) veya (C) cevabını seçin. Bağlam ayrıntıları aşağıdaki gibidir: {} Soru: {} (A): {} (B): {} (C): {} Cevap:",
    },
}
